version: '3'
services:
  mssql-server:
    #image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    image:  mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: "Y"
      #SA_PASSWORD: "Bsr4762ha7is44*9"
      MSSQL_SA_PASSWORD: "Bsr4762ha7is44*9"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - C:\dados\volumes\sqlserver:/var/opt/mssql/data
  usuario-app:
    build: .
    environment:
      DbServer: "mssql-server"
      DbPort: "1433"
      DbUser: "SA"
      Password: "Bsr4762ha7is44*9"
      Database: "GrupoGBIControleUsuarioProd"
    ports: 
      - "8090:80"
