version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge 

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Bsr4762ha7is44*9"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    networks:
      - dockerapi-dev  
    volumes:
      - C:\dados\volumes\sqlserver:/var/opt/mssql/data

  usuario-app:
    build: .
    environment:
      DbServer: "mssql-server"
      DbPort: "1433"
      DbUser: "SA"
      Password: "Bsr4762ha7is44*9"
      Database: "GrupoGBIControleUsuarioProd"
    ports: 
      - "8090:80"
    networks:
      - dockerapi-dev  
